### ISSUE TITLE
Testing Java UIO on Orange Pi

### ISSUE THREAD

**Issue by jkeerati** [sgjava/javauio#1]
First of all, I would like to say a big "Thank you!" for making this project. This project is very promising especially for its cross platform and performance. 

I'm trying to use Java UIO on Orange Pi PC Plus. Since this SBC is using the same CPU as NanoPi M1 (Allwinner H3). I think I could use NanoPi M1 "input file" to work with Orange Pi PC Plus. I could install and compile Java UIO on Orange Pi successfully. However,  when I tried to run LedBlink demo, it didn't work out. So, I thought it didn't work because I use the wrong input file. So, I tried to read the code to find a way to specify the input file, but couldn't find any. So, I take a look at another source code (Gen.java) and see that it clearly has an argument to specify the input file. 

So, my question is very simple. How could I specify the input file in the demo program?

Sorry if I'm asking a silly. I'm an experienced java programmer, but I'm quite new for low-level programming (e.g. GPIO) in java.

**Comment by sgjava** [comment]
@jkeerati so the input files are for MMIO GPIO (https://github.com/sgjava/javauio/tree/main/tools#high-performance-gpio-using-mmio) and are tied to the boards chipset. Are you using Armbian? The first thing you should do is test GPIO pin with LED by installing GPIOD `sudo apt install -y gpiod` then take a look at https://www.ics.com/blog/gpio-programming-exploring-libgpiod-library. Java UIO uses the same pin numbers and library.

Once you verify you can test with gpiod then use `--help` on LedBlink to get argument list.

**Comment by jkeerati** [comment]
Thanks for your answer. Yes, I'm using Armbian. I just use GPIOD to do a simple test with Java UIO on Orange Pi PC Plus (both GPIOD and MMIO GPIO) and it is working well :)

**Comment by sgjava** [comment]
So the M1 mappings worked for MMIO? With the boards I did it should cover H2+, H3 and H5 as far as Allwinner.

**Comment by jkeerati** [comment]
Yes, NanoPi M1 (m1-map.properties) MMIO property file is working with OrangePi PC Plus, but I think the pin arrangement on each SBC may differ. For example, the pin "203" is not present in OrangePi PC Plus.
![OrangePi-PCPlus-pin](https://user-images.githubusercontent.com/5717780/150092028-6ee12443-b075-42e6-8277-e54c6b02af0d.png)

**Comment by sgjava** [comment]
Yes pin mapping will be different, but the registers are the same. 203 is GPIOG11 on the M1 (the G is the group name) https://wiki.friendlyarm.com/wiki/index.php/NanoPi_M1#Layout

Notice how you have PA, PC, PD, etc.? That's probably the Orange PI groups. See https://github.com/sgjava/javauio/blob/e42f04d430c9641730071941aabeda97b2564350/periphery/src/main/resources/m1.properties#L26

Hope that makes sense. You may need to make a copy of the properties and change https://github.com/sgjava/javauio/blob/e42f04d430c9641730071941aabeda97b2564350/periphery/src/main/resources/m1.properties#L18 (these are the same as GPIOD) and https://github.com/sgjava/javauio/blob/e42f04d430c9641730071941aabeda97b2564350/periphery/src/main/resources/m1.properties#L22

The memory mapping is a little more challenging to change https://github.com/sgjava/javauio/blob/main/periphery/src/main/resources/m1-map.properties

I provide the tools https://github.com/sgjava/javauio/tree/main/tools#high-performance-gpio-using-mmio so you can use GPIOD pin mapping to get memory addresses. This is a lot more efficient than using the datasheet and offsets.

**Comment by jkeerati** [comment]
I'll try to make property file for OrangePi, but I think I need to learn more about MMIO. My current knowledge about MMIO is rather limited (just enough to do a simple testing). I think it would requires a deeper knowledge to understand and create property file.

**Comment by sgjava** [comment]
@jkeerati you can start with the H3 datasheet http://wiki.friendlyarm.com/wiki/images/4/4b/Allwinner_H3_Datasheet_V1.2.pdf, but honestly I've done all the hard work. You mainly just need to map what I pointed out above. A totally new chip takes me a few hours with my tools. If you did it by hand like other libraries it would take days. If I had a OPi I would have mapped it already :) Just fire up MemScan and try one of the pins. Looks like H3 GPIO chip starts at 0x1c20800. If you want me to give you and example let me know.
